### ISSUE TITLE
Cakebrew wont load; Spinny wheel only.

### ISSUE THREAD

**Issue by njt1982** [brunophilipe/Cakebrew#144]
![image](https://cloud.githubusercontent.com/assets/384976/9939876/79bf58ac-5d64-11e5-86e8-bc83309bc9c6.png)

This is all I get. It used to load very quickly and now it... well.. doesn't.

Does it log anywhere?

**Comment by njt1982** [comment]
All I see in console is this:

```
17/09/2015 17:50:45.473 Cakebrew[60778]: brew: /usr/local/bin/brew
17/09/2015 17:50:45.473 Cakebrew[60778]: cellar: /usr/local/Cellar
```

**Comment by njt1982** [comment]
```
$ brew doctor
Your system is ready to brew.
```

**Comment by njt1982** [comment]
I gave tried deleting and reinstalling (deleting using AppCleaner and reinstalling from a fresh DMG download).

**Comment by njt1982** [comment]
Interestingly, *Brew cleanup* from the Tools menu works...

![image](https://cloud.githubusercontent.com/assets/384976/9940030/2bdc3adc-5d65-11e5-96e3-420835860c60.png)

**Comment by brunophilipe** [comment]
Are you running El Capitan?

**Comment by njt1982** [comment]
Nope, Yosemite 10.10.5...
![pasted_image_17_09_2015_23_20](https://cloud.githubusercontent.com/assets/384976/9947532/bd7fa19a-5d92-11e5-9ae5-e6f6427a77d8.png)

**Comment by njt1982** [comment]
@brunophilipe Is there anything I can run to help debug? Does it log anywhere? Can it be fired up in debug/vebose mode?

**Comment by njt1982** [comment]
Running it from Terminal shows this:

![image](https://cloud.githubusercontent.com/assets/384976/9947577/05df1d76-5d93-11e5-88c3-593cd29d8ca5.png)

**Comment by brunophilipe** [comment]
Hm that's definitely the problem. I'll have a look at that. Thanks!

**Comment by brunophilipe** [comment]
Please test this version: https://www.cakebrew.com/files/cakebrew-1.1.3.zip

**Comment by njt1982** [comment]
No dice...

![image](https://cloud.githubusercontent.com/assets/384976/9947940/6b99668c-5d96-11e5-9618-daf3aaea37bc.png)

How long should I leave it spinning? ;-) What is a resonable time to assume that it really isn't working (vs just taking ages?)

**Comment by njt1982** [comment]
After ~1 minute the spinning wheel stops.

On a positive note; no more cache file error ;-)

**Comment by brunophilipe** [comment]
This should not take more than a few seconds.
There is probably something wrong with your Caches file. Please move the entire directory below to the trash:
`/Users/<YOUR_USERNAME>/Library/Caches/com.brunophilipe.Cakebrew/`

**Comment by njt1982** [comment]
tried - no luck (the folder looked empty anyway).

Tried both 1.1.2 and 1.1.3 after removing the cache folder.

**Comment by brunophilipe** [comment]
Please check with this version, and see what is the console output:

https://www.cakebrew.com/files/cakebrew-1.1.3-beta2.zip

**Comment by njt1982** [comment]
Nope - no luck... Same problem.

![image](https://cloud.githubusercontent.com/assets/384976/9957153/c4c4c4ae-5df5-11e5-888c-29ca120bd425.png)

(I deleted the caches before hand again too, just in case - although the folder looked empty).

**Comment by JoyceBabu** [comment]
I am also getting the same error

    Could not load cache file. -[BPAppDelegate urlForApplicationCachesFolder] returned nil!

**Comment by njt1982** [comment]
@JoyceBabu  at least its not just me.

I wonder what has changed recently thats broken it. The problem is, I dont use it every day (more like once or twice a month to check for available updates). But I use my laptop for 9+hrs a day, so anything could have changed.

**Comment by JoyceBabu** [comment]
Mine is a new installation. I found out Cakebrew only today.

**Comment by njt1982** [comment]
@JoyceBabu you on 10.10.5 too? When did `.5` come out? Maybe last time I used it was `.4`??!

**Comment by JoyceBabu** [comment]
Yes, I am also running 10.10.5. I don't remember updating in the past few weeks.

**Comment by brunophilipe** [comment]
The thing is that the current version of cakebrew was released several weeks ago, so this is a really bizarre error. I am slowly investigating it since I'm not having a lot of time right now. I might have more time on Sunday night.

**Comment by JoyceBabu** [comment]
I tracked it to `[self.task waitUntilExit];` under `(BOOL)performBrewCommandWithArguments:(NSArray*)arguments dataReturnBlock:(void (^)(NSString*))block`. The `brew search` task is not exiting.

I can see it running in my process list, even after 1 hour.

```
iMac:~ joyce$ ps aux | grep brew
joyce           65626   0.4  0.0  2441988    664 s021  S+    1:58AM   0:00.00 grep brew
joyce           85525   0.1  0.2  2612380  17972   ??  S    11:55PM   0:22.83 /Users/joyce/Library/Developer/Xcode/DerivedData/Cakebrew-egavemoetogalmfuammuicqjntug/Build/Products/Debug/Cakebrew.app/Contents/MacOS/Cakebrew -NSDocumentRevisionsDebugMode YES
joyce           87181   0.0  0.0  2498432   1780   ??  S    11:55PM   0:00.21 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb search
joyce           86886   0.0  0.0  2513004    848   ??  S    11:55PM   0:00.23 /usr/local/bin/bash -l -c echo "+++++Cakebrew+++++";brew search
joyce           58246   0.0  0.0  2500480   1892   ??  S     1:43AM   0:00.19 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb search
joyce           57975   0.0  0.0  2490112    700   ??  S     1:43AM   0:00.24 /bin/bash -l -c echo "+++++Cakebrew+++++";brew search
joyce           55187   0.0  0.4  2572652  35528   ??  SX    1:39AM   0:00.83 /Users/joyce/Library/Developer/Xcode/DerivedData/Cakebrew-egavemoetogalmfuammuicqjntug/Build/Products/Debug/Cakebrew.app/Contents/MacOS/Cakebrew -NSDocumentRevisionsDebugMode YES
```

**Comment by JoyceBabu** [comment]
I killed the hung `brew search` process using `kill <pid>` and after than Cakebrew loaded. It is now working fine (even after clearing `~/Library/Caches/com.brunophilipe.Cake`).

**Comment by brunophilipe** [comment]
Can you reproduce this with the current release version (1.1.2)?

**Comment by brunophilipe** [comment]
This used to happen on OS X Lion, where an NSTask running `brew list` would hang forever. That's why support for it was dropped. I hope this is a bug with brew that is fixed soon, otherwise Cakebrew will halt working completely.

**Comment by njt1982** [comment]
I can confirm @JoyceBabu 's workaround works for me too:

```
NicholasMacBookPro:~ nthompson$ ps aux | grep brew
nthompson       13255   1.8  0.2  2619624  26336   ??  U    10:14am   0:00.53 /Applications/Cakebrew.app/Contents/MacOS/Cakebrew
nthompson       13756   0.0  0.0  2423356    208 s001  R+   10:15am   0:00.00 grep brew
nthompson       13745   0.0  0.1  2490840  16024   ??  S    10:15am   0:00.19 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb search
nthompson       13670   0.0  0.0  2466136   3032   ??  S    10:14am   0:00.06 /bin/bash -l -c echo "+++++Cakebrew+++++";brew search
NicholasMacBookPro:~ nthompson$ kill 13670
```

@brunophilipe why does it run search at the beginning?

**Comment by brunophilipe** [comment]
'brew search' is the command used to list all available formulae. I've been working on a different approach, by browsing the brew Cellar and Library directories, but I definitely have not had enough time in the past month or so.

**Comment by njt1982** [comment]
@brunophilipe not a problem, as a fellow open source maintainer I fully understand the time restraints of life :)

**Comment by ChrisChinchilla** [comment]
@brunophilipe I have the same problem with El Capitan, anything I can do to help debug?

Never had the issue with Yosemite, typically after a restart it will work for a bit. Interestingly I have the same problem with Adobe Creative Cloud, I doubt it's related, but you never know!

**Comment by brunophilipe** [comment]
@ChrisChinchilla Ideally, if you are able to, the best way to find the cause of this is by cloning the repo and running Cakebrew from Xcode, and set some breakpoints to see where it halts. Other than that, there's not much that can be done.

In the end this should be fixed my moving Cakebrew away from console-parsing and towards listing the contents of brew's Cellar+Library directories.

**Comment by ChrisChinchilla** [comment]
@brunophilipe this seems to have been fixed with 10.11.1 but I will update this thread if it hasn't.

**Comment by brunophilipe** [comment]
Awesome! 👍

**Comment by njt1982** [comment]
@ChrisChinchilla Why would an OS X release break this? 

I just tried loading it and was prompted to update to 1.1.4 and I still get the spinning wheel on 10.10.5...

![image](https://cloud.githubusercontent.com/assets/384976/10688117/d1cca006-7969-11e5-97f5-ab7b58245da0.png)

![image](https://cloud.githubusercontent.com/assets/384976/10688119/d735d986-7969-11e5-8fb5-05b418edc64e.png)

**Comment by ChrisChinchilla** [comment]
@njt1982 I can't speak for releases prior to 10.11 as I _never_ had an problems before.

It introduced some extra security features that have affected several apps, including Adobe and Microsoft as well as more command line style tools such as homebrew. Basically apps that do things a non-Apple way.

I'm still not even sure that 10.11.1 has fixed the issue yet, I would typically start getting this issue after a day.

**Comment by JoyceBabu** [comment]
Cakebrew is now working for me, after I updated to OSX 10.11.1 and Cakebrew 1.1.4.

**Comment by ChrisChinchilla** [comment]
@brunophilipe Nope, sorry after a day of my machine being on, back to the same problem, and again the same problem also with Adobe Creative Cloud. So there's something more fundamentally broken than just with Cakebrew.

How do you suggest we help debug this, bearing in mind the above? Anything from console output maybe?

**Comment by brunophilipe** [comment]
@ChrisChinchilla If the UI is not frozen, as in the "spinny wheel" is actually animating, this means that it is waiting on the background task running the NSTask that communicates with Homebrew. This sudden surge of instances of this problem could indicate a bug in Apple's side. If that's the case, there is not much I can do.

I mean, I could do a hack and make it work using low-level posix functions, but this would be very complicated, only to have it eventually fixed by Apple, meaning all that work was pointless.

If I have some time this week I will make a debug build that heavily logs the background tasks and ask you people to try it and see what appears to be happening.

**Comment by njt1982** [comment]
Thanks @brunophilipe

**Comment by ChrisChinchilla** [comment]
@brunophilipe I feel like have seen a lot of UserEventAgent entries in console when running Cake Brew recently. Not sure if that helps at all.

Grr, most annoying when these things happen to small developers :(

**Comment by herrbischoff** [comment]
I encountered the spinning problem just now, which renders this application basically useless.

```bash
$ ps aux | grep brew
[REDACTED]       55977   1.5  0.4  2657892  59220   ??  S    10:44AM   0:03.28 /Applications/Cakebrew.app/Contents/MacOS/Cakebrew
[REDACTED]       57372   0.0  0.0  2444052    796 s000  S+   10:47AM   0:00.00 grep --color=auto brew
[REDACTED]       56065   0.0  0.1  2483672  19336   ??  S    10:44AM   0:00.19 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb search
```

After I forced PID 56065 to exit with `kill -9`, the GUI immediately started to work.

### Console

```
15.01.16 10:44:14,385 Cakebrew[55977]: cellar: /usr/local/Cellar
15.01.16 10:44:14,393 Cakebrew[55977]: SecTaskLoadEntitlements failed error=22
15.01.16 10:44:14,393 Cakebrew[55977]: SecTaskLoadEntitlements failed error=22
15.01.16 10:44:14,393 Cakebrew[55977]: SecTaskLoadEntitlements failed error=22
```

### Info

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
```

Cakebrew Version 1.1.5 (Build 347)

**Comment by ChrisChinchilla** [comment]
@herrbischoff If you mean killing `/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb search` I tried your steps and didn't work for me.

Boo :(

**Comment by herrbischoff** [comment]
@ChrisChinchilla: Well, Cakebrew has stopped working for me again. I'm removing it now, it's broken. Basically not more than a limited (and non-working) GUI anyway. I'm back to my old trusty shell alias:

```bash
update='sudo softwareupdate -i -a && brew update && brew upgrade && brew cleanup && npm install npm -g && npm update -g && sudo gem update --system && sudo gem update'
```

**Comment by ChrisChinchilla** [comment]
@herrbischoff Nice script, I was thinking of creating something like that anyway :)

**Comment by brunophilipe** [comment]
Hello everybody. This is a bug that (as you may see) have been plaguing Homebrew for a very long time. At first it was a problem in 10.7 Lion only, and it was one of the reasons support for that version was removed.

Now it seems the bug is affecting any OS X users.

However, as much as I have tried, I can't reproduce the error on any of my machines. I have tried on two new OS X installations I had access to on different machines (iMac and Macbook Pro), and they all work flawlessly.

I am trying to gather data that will allow me to fix this bug, and since I can't reproduce it, I need your help.
Please past below the following data if you are having this problem:

```
OS X Version:
Cakebrew Version:
Homebrew Version:
List of tapped repos:
List of installed formulae:
```

Below there are instructions on how to get this info:

* OS X Version: In the Menu Bar: `Apple Menu > About This Mac`
* Cakebrew Version: With Cakebrew opened, in the Menu Bar: `Cakebrew > About Cakebrew`
* Homebrew Version: In a shell session: `brew --version`
* List of tapped repos: In a shell session: `brew tap`
* List of installed formulae: In a shell session: `brew list --versions`

Thanks a lot!

**Comment by anbykov** [comment]
- OS X Version: 10.9.5;
- Cakebrew Version: 1.1.5 (Build 347);
- Homebrew Version: Homebrew 0.9.5 (git revision 839bb; last commit 2016-01-23);
- List of tapped repos:
  - homebrew/apache
 - homebrew/dupes
 - homebrew/fuse
 - homebrew/php
 - homebrew/versions
 - josegonzalez/php
-  List of installed formulae:
 - apr 1.5.2
 - apr-util 1.5.4_1
 - cpulimit 0.1
 - curl 7.46.0
 - freetype 2.6_1
 - gettext 0.19.6
 - httpd24 2.4.16
 - icu4c 56.1
 - jpeg 8d
 - libpng 1.6.20
 - openssl 1.0.2e
 - osxfuse 2.8.0
 - pcre 8.38
 - pkg-config 0.28
 - readline 6.3.8
 - unixodbc 2.3.2_1
 - zlib 1.2.8

**Comment by m-urban** [comment]
I have just updated my Mavericks installation to El Capitan and am seeing this problem now, too. Killing the `brew search` (temporarily?) fixed it for me.

OS X Version: 10.11.3
Shell used: /bin/bash
Cake brew Version:1.1.5 (Build 347)
Homebrei Version: Homebrew 0.9.5 (git revision 839bb; last commit 2016-01-23)
List of tapped repos:
- caskroom/cask
- homebrew/completions
- homebrew/fuse
- homebrew/games
- homebrew/php
- homebrew/python
- homebrew/science
- homebrew/versions
- homebrew/x11
List of installed formulae:
- bash-completion 1.3
- bchunk 1.2.0
- boost 1.60.0_1
- brew-cask 0.60.1
- brew-cask-completion 2.0
- cairo 1.14.6
- cloog 0.18.4
- cmake 3.4.2
- coreutils 8.25
- curl 7.46.0
- dirmngr 1.1.1_1
- dosbox 0.74
- e2fsprogs 1.42.13
- eigen 3.2.7
- exif 0.6.21
- exiftags 1.01
- exiftool 10.08
- ext2fuse 0.8.1
- ext4fuse 0.1.3
- eye-d3 0.7.8
- faac 1.28
- ffmpeg 2.8.5
- fluid-synth 1.1.6
- fontconfig 2.11.1
- freetype 2.6_1
- gcc 5.3.0
- gd 2.1.1
- gdbm 1.11
- gettext 0.19.7
- git 2.7.0
- glib 2.46.2
- gmp 6.1.0
- gnuplot 5.0.2
- gobject-introspection 1.46.0_1
- icu4c 56.1
- ilmbase 2.2.0
- imessage-ruby 0.3.1
- isl 0.15
- jasper 1.900.1
- jpeg 8d
- lame 3.99.5
- libassuan 2.4.2
- libexif 0.6.21
- libffi 3.0.13
- libgcrypt 1.6.4_1
- libgpg-error 1.21
- libksba 1.3.3
- libmpc 1.0.3
- libpng 1.6.20
- libssh2 1.6.0
- libsvg 0.1.4_1
- libsvg-cairo 0.1.6_1
- libtiff 4.0.6
- libusb 1.0.20
- libusb-compat 0.1.5
- libvo-aacenc 0.1.3
- libxml2 2.9.3
- libyaml 0.1.6_1
- little-cms2 2.7
- lua 5.2.4_3
- mcrypt 2.6.8
- mercurial 3.6.3
- mhash 0.9.9.9
- midnight-commander 4.8.15
- mpfr 3.1.3
- mysql 5.7.10
- nmap 7.01
- numpy 1.10.4
- opencv 2.4.12_2
- openexr 2.2.0
- openjpeg 1.5.2_1
- openssl 1.0.2e_1
- php56 5.6.17
- php56-mcrypt 5.6.17
- phpmyadmin 4.5.3.1
- pinentry 0.9.7
- pixman 0.32.8
- pkg-config 0.29
- poppler 0.40.0
- popt 1.16
- pth 2.0.7
- python 2.7.11
- readline 6.3.8
- s-lang 2.3.0
- sane-backends 1.0.24_1
- sdl 1.2.15
- sdl_net 1.2.8
- sdl_sound 1.0.3
- smartmontools 6.4
- sqlite 3.10.2
- svg2pdf 0.1.3
- terminal-notifier 1.6.3
- texi2html 5.0
- unar 1.9.1
- unixodbc 2.3.2_1
- x264 r2601
- xctool 0.2.7
- xvid 1.3.4
- xz 5.2.2
- yasm 1.3.0
- youtube-dl 2016.01.15 2016.01.23

**Comment by ChrisChinchilla** [comment]
OS X version - 10.11.3 (15D21)
Shell - /bin/bash
Cakebrew - 1.1.3 (Build 324)
Homebrew 0.9.5 (git revision 84d7; last commit 2016-01-22)

Taps
caskroom/cask
homebrew/completions
homebrew/devel-only
homebrew/php
zoidbergwill/python

Brew List
autoconf 2.69
bash-completion 1.3
brew-cask 0.60.1
brew-cask-completion 2.0
bundler-completion 2
composer 1.0.0-alpha11
docker-completion 1.8.1
flow 0.20.1
freetype 2.6_1
gdbm 1.11
gem-completion 2
gettext 0.19.7
git 2.7.0
gmp 6.1.0
httpie 0.9.3
icu4c 56.1
imagemagick 6.9.3-0
jpeg 8d
libpng 1.6.20
libtiff 4.0.6
libtool 2.4.6
libxml2 2.9.3
libyaml 0.1.6_1
mariadb 10.1.10
mongodb 3.2.1
node 5.5.0
nspr 4.11
nvm 0.30.1
openssl 1.0.2e_1
pandoc 1.16.0.2
pcre 8.38
php56 5.6.17
pkg-config 0.29
python34 3.4.3
rails-completion 2
rake-completion 1
readline 6.3.8
ruby 2.3.0
ruby-completion 2
spidermonkey 1.8.5_1
sqlite 3.10.2
unixodbc 2.3.2_1
vagrant-completion 1.7.4
varnish 4.1.0
watchman 4.1.0
wget 1.17.1
wxmac 3.0.2_2
xz 5.2.2

**Comment by idoo** [comment]
```
/Applications/Cakebrew.app/Contents/MacOS/Cakebrew ; exit;
2016-02-10 14:31:05.128 Cakebrew[35840:61354089] cellar: /usr/local/Cellar
```

**Comment by njt1982** [comment]
Interesting, I just installed it on a clean El Capitain setup and loaded it, expecting it to be broken. The wheel was there for several seconds. Then it worked.

**Comment by idoo** [comment]
i wait ~1 hr and no result :(

**Comment by m-urban** [comment]
@idoo: @JoyceBabu described [a way to fix it in his posts above](https://github.com/brunophilipe/Cakebrew/issues/144#issuecomment-141561003) which worked for me, too.

**Comment by ChrisChinchilla** [comment]
@m-urban @JoyceBabu fixes don't work for me, I can't even kill the process.

**Comment by brunophilipe** [comment]
I recently thought of something, and honestly it is just a shot in the dark. Have you guys ever been prompted to accept the Xcode command-line tools license agreement? This is a horrible thing that was introduced to the command-line tools recently, and basically none of the tools will execute properly until you accept the terms & conditions.

To make sure you did, run the following:

* `sudo xcodebuild -license`
* press `q` to quit the license screen
* type `accept` and press enter

Then try running Cakebrew again. This shouldn't be halting Cakebrew, but who knows...

**Comment by njt1982** [comment]
Hmm. I have as I'm an amateur iPhone dev... Interesting idea.

**Comment by anbykov** [comment]
Many thanks, brunophilipe. This helped me and solve the problem.

> To make sure you did, run the following:
> sudo xcodebuild -license
> press q to quit the license screen
> type agree and press enter

**Comment by brunophilipe** [comment]
@anbykov This is very good news! I'm happy it works for you now. Thanks for the feedback. Everybody else that sill have the issue, please try the following: https://github.com/brunophilipe/Cakebrew/issues/144#issuecomment-183546970

**Comment by ChrisChinchilla** [comment]
Nope, still no fix for me. And I would have accepted this already as I do iOS development.

**Comment by bfontaine** [comment]
Same issue here; I accepted the license and `brew doctor` doesn’t report anything. I built with Xcode from the current repo (3660b1140ae77d222870b2480371eba6e32b9651).

* OS X version: 10.11.3 (15D21)
* Xcode: 7.2.1 (7C1002)
* Shell: /usr/local/bin/bash (Bash 4.3.42)
* Cakebrew version: 1.1.5 (Build 347)
* Homebrew Version: 0.9.5 (git revision dd162; last commit 2016-02-17)
* 27 taps & 169 formulae: https://gist.github.com/bfontaine/ecad153e249fc6b6cdbc

Removing the cache and restarting doesn’t work. Killing the `brew search` process did the trick as mentioned by others.

Also note that you can get a detailed list of all formulae in JSON by using `brew info --all --json=v1`. It takes a lot more time (on my mac `brew search` completes in .5 seconds while this takes almost one minute) but if you need info about a formula in a parseable format this is the command. Use `brew info --json=v1 foo` to get some info about the `foo` formula.

**Comment by brunophilipe** [comment]
Hey @bfontaine! Awesome that you can compile it on your machine and reproduce the error. Can you please try commit 8f8b6140da9079f16746c57b4283bd1b35d49d85, it is the HEAD of the `dev` branch. Thanks!

**Comment by bfontaine** [comment]
Doesn’t fix the issue :cry: 

I tried to launch the `.app` I built earlier again and this time it worked as expected, as that was already pointed out: the issue appears only the first time you launch the app. I then went back to Xcode, rebuilt again, and reproduced the error. In Xcode I checked out the `dev` branch; made sure the latest commit was 8f8b6140da9079f16746c57b4283bd1b35d49d85; rebuit; and… same spinning wheel.

I’ll try to remember to see how it behaves with breakpoints tomorrow.

**Comment by bfontaine** [comment]
I think I found what’s causing the issue but I’m not familiar enough with Objective-C to verify it: I get the infinitely spinning wheel when the output of `brew search` is longer than 65,517 chars. That’s close to 2<sup>16</sup> (65,536) but not exactly that.

I have a lot of taps and thus 5700+ formulae. If I truncate the list to 4845 formulae I get 65,516 chars and it works (`brew search | wc -c` prints `65516`). If I add only one formula it jumps to 65,542 chars and I get the infinitely-spinning wheel.

I faked the output of `brew search` to return exactly 65,517 chars and it works. If I add one char I get the infinitely-spinning wheel.

Steps to reproduce:
1. `cd $(brew --prefix)`
2. In your favorite editor, open `Library/Homebrew/cmd/search.rb`. Replace `puts_columns Formula.full_names` line 13 with some code that prints one different word per line such that the total output is exactly 65,517-chars long. For example `puts ("aaa".."yfx").to_a; puts "yolo"`.
3. `rm -rf ~/Library/Caches/com.brunophilipe.Cakebrew`
4. Start Cakebrew from Xcode to ensure you run it for the first time
5. It should work but the “All Formulae” tab has all our fake formulae in it (`aaa`, `aab`, `aac`, etc)
6. Do step 2 again but this time make something that’s 65,518-chars long by adding a character at the end of `yolo`. The code becomes e.g. `puts ("aaa".."yfx").to_a; puts "yoloz"`. Do steps 3 and 4.
7. You should get the infinitely-spinning wheel.
8. :warning: Be sure to run `git checkout Library/Homebrew/cmd/search.rb` to discard all your changes.

A diff for step 2:
```diff
diff --git a/Library/Homebrew/cmd/search.rb b/Library/Homebrew/cmd/search.rb
index 8dd1ceb..ce45fde 100644
--- a/Library/Homebrew/cmd/search.rb
+++ b/Library/Homebrew/cmd/search.rb
@@ -10,7 +10,7 @@ module Homebrew
 
   def search
     if ARGV.empty?
-      puts_columns Formula.full_names
+      puts ("aaa".."yfx").to_a;puts "yolo"
     elsif ARGV.include? "--macports"
       exec_browser "https://www.macports.org/ports.php?by=name&substr=#{ARGV.next}"
     elsif ARGV.include? "--fink"
```

I should mention that I ran this on the `dev` branch, commit https://github.com/brunophilipe/Cakebrew/commit/8f8b6140da9079f16746c57b4283bd1b35d49d85 (the current `HEAD`).

@brunophilipe I hope you’ll be able to reproduce the issue with these steps.

**Comment by brunophilipe** [comment]
This is absolutely fantastic! Thank you so much!

However, for me it took more than 65,517 characters for it to halt. I had to change it to `puts ("aaaaa".."zzzzz").to_a; puts "yolo"` to trigger the problem. Either way, it should make no difference, since Cakebrew should be able to parse any amount of data.

I am going to investigate it now. I hope this is not a limitation of `NSPipe` 😕

**Comment by brunophilipe** [comment]
It is a limitation indeed:

> The length of the data is limited to the buffer size of the underlying operating system. The notification includes a userInfo dictionary that contains the data read; access this object using the NSFileHandleNotificationDataItem key.

From `NSFileHandle` Class Reference.

**Comment by brunophilipe** [comment]
I am proud to say that I have (hopefully) hammered this bug down for good. Please try this RC for version 1.2: [**Download**](https://www.cakebrew.com/files/cakebrew-1.2rc1.zip)

**Comment by JoyceBabu** [comment]
Thank you @brunophilipe @bfontaine . It is working now.

**Comment by bfontaine** [comment]
Thank you @brunophilipe; it works now! :tada:

**Comment by idoo** [comment]
Thank you! Its work now :+1:

**Comment by brunophilipe** [comment]
Fantastic! :tada:

**Comment by kingmatusevich** [comment]
I'm having this problem, I installed Cakebrew for the first time today and from the beginning I got this Loading screen that won't ever end. I tried the RC here, to no avail. My process list: 

```
javiermatusevich 66716   0.4  0.3  2551984  25588   ??  U     7:16PM   0:02.91 /Applications/Cakebrew-1.2-RC1.app/Contents/MacOS/Cakebrew
javiermatusevich 66974   0.3  0.0  2424600    440 s000  R+    7:22PM   0:00.00 grep brew
javiermatusevich 66723   0.0  0.2  2471344  15472   ??  S     7:16PM   0:00.25 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Library/brew.rb config
javiermatusevich 66720   0.0  0.0  2446696   1064   ??  S     7:16PM   0:00.00 /bin/bash -l -c echo "+++++Cakebrew+++++";brew config
```

**Comment by brunophilipe** [comment]
Hello @kingmatusevich, please try this fix: https://github.com/brunophilipe/Cakebrew/issues/144#issuecomment-183546970

**Comment by kingmatusevich** [comment]
I tried accepting the Xcode license and I'm still facing the same issue.

**Comment by brunophilipe** [comment]
The problem was caused by a buffer exhaustion, and the current fix makes sure that does not happen, so you are definitely facing another problem. Here are some things I can think on the top of my head that might help you find the problem:

* Just to make sure: run `brew config` from your terminal.
* Then run `/bin/bash -l -c "brew config"`
* Do you use the default OS X Terminal? Have you changed your default shell from `/bin/bash`? Misconfigured shell profiles are a known cause of Cakebrew problems. Check [these instructions](https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell) for `zsh` for example.
* Empty the cache folder: `rm -rf ~/Library/Caches/com.brunophilipe.Cakebrew`

That's all I can think of right now.

**Comment by kingmatusevich** [comment]
I tried everything you said, everything worked as expected. I use the default OS X Terminal, and haven't changed my default shell. 
The output from `brew config`:

```
Javiers-Mac-mini:build javiermatusevich$ /bin/bash -l -c "brew config"
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 14b0638184ace2f5e5b179130025788d9a724e8c
Last commit: 31 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65, 1.6.0_65-b14-468
```

**Comment by bfontaine** [comment]
@kingmatusevich Just to be sure; did you try the version mentioned in https://github.com/brunophilipe/Cakebrew/issues/144#issuecomment-186018369?

**Comment by kingmatusevich** [comment]
100% sure. Cakebrew-1.2-RC1

**Comment by kingmatusevich** [comment]
![screen shot 2016-02-21 at 11 40 29 p m](https://cloud.githubusercontent.com/assets/1448511/13208114/8facce90-d8f4-11e5-9a5c-d903f43d44ec.png)

**Comment by ChrisChinchilla** [comment]
So far, this seems to be working for me too :)

**Comment by bfontaine** [comment]
@kingmatusevich Does `brew doctor` say something?

**Comment by kingmatusevich** [comment]
I must note `brew` is working correctly for all my CLI use, however, here's my output from `brew doctor`:

```
Javiers-Mac-mini:~ javiermatusevich$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/man8

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

**Comment by bfontaine** [comment]
@kingmatusevich Unless @brunophilipe has a better idea on this you should probably run Cakebrew from Xcode and use breakpoints to spot where it’s spending all that time.

**Comment by kingmatusevich** [comment]
Is there a tag with the source of 1.2-RC1 somewhere I can checkout?

**Comment by brunophilipe** [comment]
Yes sorry, I had forgotten to push my tags. https://github.com/brunophilipe/Cakebrew/releases/tag/v1.2-RC

Or you can try the HEAD version as well.

**Comment by kingmatusevich** [comment]
Great, I'll try debugging it in Xcode in the first time slot I got available.

**Comment by kingmatusevich** [comment]
I updated to 1.2 and It worked. 😊

**Comment by brunophilipe** [comment]
Awesome! I'll close this issue now.
