### ISSUE TITLE
Installed and outdated count no longer showing

### ISSUE THREAD

**Issue by RichDonnellan** [brunophilipe/Cakebrew#220]
Holla! Adding this issue even though there hasn't been much action here.

### Problem

On Catalina (`10.5.3`) and after "Updating Homebrew", the count for "Installed" and "Outdated" disappear even though it existed prior to updating and indeed has an update.

![image](https://user-images.githubusercontent.com/7773718/75372846-facb3880-587d-11ea-8e7c-a35393448333.png)

**Comment by bligny** [comment]
I confirm the bug, I get the same on my Mac (also Catalina 10.15.3)

**Comment by danielbmeireles** [comment]
I also confirm the bug. I managed to fix it cleaning the Cakebrew cache (using the Cleaner One Lite).

**Comment by brunophilipe** [comment]
Fixed in a9036a0158df9ac77434470e4f9a48f9704aee84

**Comment by RichDonnellan** [comment]
@brunophilipe I'm still seeing issues on the new release. It's not showing any installed formulas after updating and installing.

![image](https://user-images.githubusercontent.com/7773718/107834820-3fc8d300-6d4c-11eb-8a76-e79e48bd2fec.png)

**Comment by brunophilipe** [comment]
Yes, there was another issue which was fixed in 778008a95036c324c8f29b8b94cfb07377073061 and should be included in the next update
